# Generated by Django 5.2.4 on 2025-07-31 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=100)),
                ('seria_id', models.IntegerField()),
                ('phone', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='room_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('context', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('seria_id', models.IntegerField()),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_activ', models.BooleanField(default=True)),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mehmonhona.employee')),
                ('id_room_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mehmonhona.room_size')),
                ('id_room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mehmonhona.category')),
            ],
        ),
        migrations.CreateModel(
            name='deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mehmonhona.rooms')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mehmonhona.users')),
            ],
        ),
    ]
