# Generated by Django 5.2.4 on 2025-08-01 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mehmonhona', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='deal',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.RenameModel(
            old_name='room_size',
            new_name='RoomSize',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mehmonhona.employee')),
                ('id_room_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mehmonhona.roomsize')),
                ('id_room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mehmonhona.category')),
            ],
        ),
        migrations.AlterField(
            model_name='deal',
            name='id_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mehmonhona.room'),
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
